from fpdf import FPDF
import datetime
import re


class PDFExporter(FPDF):
    # ------------------------------------------------------------------ #
    #  Layout constants (all in mm, A4 page = 210 × 297)                  #
    # ------------------------------------------------------------------ #
    L_MARGIN = 15          # left margin
    R_MARGIN = 15          # right margin
    T_MARGIN = 22          # top margin
    CONTENT_W = 180        # 210 - 15 - 15
    LINE_H = 6             # standard cell line-height
    SMALL_LINE_H = 5       # line-height for monospace / tight sections

    # -- Two-column table layout (within CONTENT_W = 180) ---------------#
    COL1_W = 32            # "Phase / Index" column
    COL2_W = 148           # "Description" column   (32+148 = 180 ✓)

    # -- Colour palette --------------------------------------------------#
    C_DARK   = (30, 41, 59)    # Slate-800  – primary dark
    C_BLUE   = (14, 165, 233)  # Sky-500    – accent
    C_MID    = (51, 65, 85)    # Slate-700  – body text
    C_FAINT  = (100, 116, 139) # Slate-500  – subtle text
    C_LIGHT  = (248, 250, 252) # Slate-50   – page background tint
    C_ROW_H  = (226, 232, 240) # Slate-200  – table header row
    C_ROW_ODD = (241, 245, 249)# Slate-100  – alternating row
    C_WHITE  = (255, 255, 255)

    def __init__(self, agent_data: dict):
        super().__init__()
        self.agent_data = agent_data
        self._row_index = 0   # used for alternating row colours

        self.set_margins(self.L_MARGIN, self.T_MARGIN, self.R_MARGIN)
        self.set_auto_page_break(auto=True, margin=20)
        self.add_page()

    # ================================================================== #
    #  Header / Footer                                                     #
    # ================================================================== #
    def header(self):
        if self.page_no() == 1:
            # Solid dark banner
            self.set_fill_color(*self.C_DARK)
            self.rect(0, 0, 210, 55, 'F')

            # Title
            self.set_font("helvetica", "B", 22)
            self.set_text_color(*self.C_WHITE)
            self.set_xy(0, 12)
            self.cell(210, 14, "STRATEGIC EXECUTION PLAN", align="C")

            # Subtitle bar
            self.set_font("helvetica", "", 9)
            self.set_text_color(148, 163, 184)  # Slate-400
            self.set_xy(0, 30)
            self.cell(
                210, 8,
                f"Generated by AI Agentic Planner  |  Groq Core  |  "
                f"{datetime.datetime.now().strftime('%d %B %Y')}",
                align="C",
            )

            # Thin accent line below banner
            self.set_fill_color(*self.C_BLUE)
            self.rect(0, 46, 210, 2, 'F')
        else:
            # Compact running header
            self.set_fill_color(*self.C_DARK)
            self.rect(0, 0, 210, 12, 'F')
            self.set_font("helvetica", "I", 7)
            self.set_text_color(200, 200, 200)
            title = self.clean_text(self.agent_data.get("title", "AI Project"))
            self.set_xy(self.L_MARGIN, 2)
            self.cell(self.CONTENT_W, 8, f"Strategic Plan: {title}", align="R")

    def footer(self):
        self.set_y(-14)
        self.set_font("helvetica", "I", 7.5)
        self.set_text_color(*self.C_FAINT)
        self.set_x(self.L_MARGIN)
        self.cell(
            self.CONTENT_W, 8,
            f"Confidential Strategic Document  |  Page {self.page_no()}",
            align="C",
        )

    # ================================================================== #
    #  Helpers                                                             #
    # ================================================================== #
    def clean_text(self, text: str) -> str:
        """Sanitise text so fpdf's latin-1 encoding never chokes."""
        if not text:
            return ""
        replacements = {
            # Dashes & quotes
            '\u2011': '-',  '\u2013': '-',  '\u2014': '-',
            '\u2018': "'",  '\u2019': "'",
            '\u201c': '"',  '\u201d': '"',
            # Bullets & symbols
            '\u2022': '-',  '\u2023': '-',  '\u2043': '-',
            '\u25e6': '-',  '\u2026': '...','\u00a0': ' ',
            # Arrows
            '\u2192': '->','\u2190': '<-', '\u2194': '<->',
            '\u21d2': '=>', '\u21d0': '<=',
            # Misc symbols
            '\u25b6': '>',  '\u25c0': '<',
            '\u2714': '[x]','\u2718': '[!]',
            '\u00b7': '-',  '\u2027': '-',
            '\u25aa': '-',  '\u25cf': '-',
            '\u2605': '*',  '\u2606': '*',
            '\u00e2': 'a',  # common corrupt UTF-8 artifact
        }
        for src, dst in replacements.items():
            text = text.replace(src, dst)
        # Final safety net: drop anything still outside latin-1
        return text.encode('latin-1', 'replace').decode('latin-1')

    def _reset_x(self):
        """Always reset X to the left margin before multi_cell calls."""
        self.set_x(self.L_MARGIN)

    def ensure_space(self, needed_h: float):
        """Add a new page if there is not enough vertical room."""
        available = self.h - self.b_margin - self.get_y()
        if needed_h > available:
            self.add_page()
            self.set_y(self.T_MARGIN + (14 if self.page_no() > 1 else 0))

    def _estimate_lines(self, text: str, width: float) -> int:
        """Rough line-count estimate for a given column width."""
        text = self.clean_text(text)
        if not text:
            return 1
        total = 0
        for para in text.split("\n"):
            para = para.strip()
            if not para:
                total += 1
                continue
            words = para.split()
            if not words:
                total += 1
                continue
            cur, lines = words[0], 1
            for w in words[1:]:
                candidate = f"{cur} {w}"
                if self.get_string_width(candidate) <= width:
                    cur = candidate
                else:
                    lines += 1
                    cur = w
            total += lines
        return max(1, total)

    # ================================================================== #
    #  Section header box                                                  #
    # ================================================================== #
    def draw_section_box(self, title: str):
        self.ensure_space(20)
        self.ln(5)

        y = self.get_y()

        # Background fill
        self.set_fill_color(*self.C_ROW_ODD)
        self.rect(self.L_MARGIN, y, self.CONTENT_W, 11, 'F')

        # Left accent bar
        self.set_fill_color(*self.C_BLUE)
        self.rect(self.L_MARGIN, y, 3, 11, 'F')

        # Section title text
        self.set_font("helvetica", "B", 11)
        self.set_text_color(*self.C_DARK)
        self.set_xy(self.L_MARGIN + 5, y)
        self.cell(self.CONTENT_W - 5, 11, title.upper(), ln=True)
        self.ln(2)

    # ================================================================== #
    #  Two-column table rows                                               #
    # ================================================================== #
    def _write_table_row(self, col1: str, col2: str, is_header: bool = False):
        col1 = self.clean_text(str(col1))
        col2 = self.clean_text(str(col2))

        # Fonts
        if is_header:
            self.set_font("helvetica", "B", 9)
        else:
            self.set_font("helvetica", "", 9)

        inner1 = self.COL1_W - 2   # inner usable widths (1 mm padding each side)
        inner2 = self.COL2_W - 2

        lines1 = self._estimate_lines(col1, inner1)
        lines2 = self._estimate_lines(col2, inner2)
        row_h  = max(lines1, lines2) * self.LINE_H + 3   # +3 padding

        self.ensure_space(row_h + 2)
        y = self.get_y()
        x = self.L_MARGIN

        # Row background
        if is_header:
            self.set_fill_color(*self.C_ROW_H)
            style1, style2 = 'DF', 'DF'
            self.set_text_color(*self.C_DARK)
        else:
            self._row_index += 1
            if self._row_index % 2 == 0:
                self.set_fill_color(*self.C_ROW_ODD)
                style1, style2 = 'DF', 'DF'
            else:
                self.set_fill_color(*self.C_WHITE)
                style1, style2 = 'D', 'D'
            self.set_text_color(*self.C_MID)

        # Draw cell borders
        self.rect(x,                  y, self.COL1_W, row_h, style1)
        self.rect(x + self.COL1_W,    y, self.COL2_W, row_h, style2)

        # Col-1 text (centred)
        self.set_xy(x + 1, y + 1)
        self.multi_cell(inner1, self.LINE_H, col1, border=0, align='C')

        # Col-2 text (left-aligned)
        self.set_xy(x + self.COL1_W + 1, y + 1)
        self.multi_cell(inner2, self.LINE_H, col2, border=0, align='L')

        self.set_y(y + row_h)

    def _process_content_to_table(self, title: str, content: str):
        """Convert AI-generated list content into a structured 2-column table."""
        self._row_index = 0
        self.draw_section_box(title)
        self._write_table_row("PHASE / #", "STRATEGIC DESCRIPTION", is_header=True)

        lines = str(content).split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Detect numbered / bulleted list items  e.g. "1. Step" or "* point"
            match = re.match(r'^([\*\-\d]+\.?)\s+(.*)', line)
            if match:
                marker, text = match.groups()
                self._write_table_row(marker, text)
            else:
                # Plain paragraph inside a list section – render as full-width text
                self.set_font("helvetica", "", 9)
                self.set_text_color(*self.C_MID)
                est = self._estimate_lines(line, self.CONTENT_W - 2)
                self.ensure_space(est * self.LINE_H + 4)
                self._reset_x()
                self.multi_cell(self.CONTENT_W, self.LINE_H, self.clean_text(line))

        self.ln(4)

    # ================================================================== #
    #  Paragraph helper                                                    #
    # ================================================================== #
    def _write_paragraph(self, text: str, font_style: str = "", font_size: int = 10,
                          color=None, line_h: float = None):
        if color is None:
            color = self.C_MID
        if line_h is None:
            line_h = self.LINE_H

        self.set_font("helvetica", font_style, font_size)
        self.set_text_color(*color)

        cleaned = self.clean_text(text)
        est = self._estimate_lines(cleaned, self.CONTENT_W)
        self.ensure_space(est * line_h + 4)
        self._reset_x()
        self.multi_cell(self.CONTENT_W, line_h, cleaned)

    # ================================================================== #
    #  Monospace / diagram helper                                          #
    # ================================================================== #
    def _write_code_block(self, text: str):
        """Render monospace text in a light-grey box."""
        self.set_font("courier", "", 8)
        self.set_text_color(*self.C_DARK)
        self.set_fill_color(*self.C_ROW_ODD)

        cleaned = self.clean_text(text)
        lines = cleaned.split('\n')

        for raw_line in lines:
            # Truncate extremely long lines to prevent single-char failures
            safe = raw_line
            max_chars = 100   # generous upper bound for Courier 8pt at 180 mm
            if len(safe) > max_chars:
                safe = safe[:max_chars] + "..."

            safe = self.clean_text(safe)
            est = self._estimate_lines(safe, self.CONTENT_W - 2)
            self.ensure_space(est * self.SMALL_LINE_H + 2)
            self._reset_x()
            self.multi_cell(self.CONTENT_W, self.SMALL_LINE_H, safe,
                            fill=True, border=0, align='L')

        # Bottom border for the whole block
        self._reset_x()
        self.set_draw_color(*self.C_FAINT)
        self.rect(self.L_MARGIN, self.get_y() - 1, self.CONTENT_W, 1, 'D')
        self.ln(3)

    # ================================================================== #
    #  Main export                                                         #
    # ================================================================== #
    def export(self, filename: str = "AI_Strategic_Plan.pdf"):
        """Build and save the PDF."""
        # ---- Project banner card (page 1) ---------------------------- #
        self.set_y(52)                       # just below header banner
        self.set_fill_color(*self.C_LIGHT)
        self.rect(self.L_MARGIN, 52, self.CONTENT_W, 18, 'F')
        self.set_fill_color(*self.C_BLUE)
        self.rect(self.L_MARGIN, 52, 4, 18, 'F')

        title_text = self.clean_text(self.agent_data.get("title", "Untitled Project"))
        self.set_font("helvetica", "B", 13)
        self.set_text_color(*self.C_DARK)
        self.set_xy(self.L_MARGIN + 7, 56)
        self.cell(self.CONTENT_W - 7, 10, f"PROJECT:  {title_text}")
        self.ln(22)

        # ---- I. Strategic Vision ------------------------------------- #
        self.draw_section_box("I. Strategic Vision")
        self._write_paragraph(
            self.agent_data.get("purpose", ""),
            font_size=10,
        )
        self.ln(3)

        # ---- II. Execution Roadmap ----------------------------------- #
        self._process_content_to_table(
            "II. Execution Roadmap",
            self.agent_data.get("flow", ""),
        )

        # ---- III. System Architecture -------------------------------- #
        self.draw_section_box("III. System Architecture")
        diag_raw = self.agent_data.get("diagram", "")
        # Strip markdown code fences if present
        diag_raw = re.sub(r'```[a-zA-Z]*\n?', '', diag_raw).strip()
        self._write_code_block(diag_raw)
        self.ln(3)

        # ---- IV. Market Intelligence & Features --------------------- #
        self._process_content_to_table(
            "IV. Market Intelligence & Features",
            self.agent_data.get("market_insights", ""),
        )

        # ---- V. Risk Assessment & Expert Review --------------------- #
        self.draw_section_box("V. Risk Assessment & Expert Review")
        self._write_paragraph(
            self.agent_data.get("feedback_out", ""),
            font_style="I",
            font_size=10,
        )
        self.ln(4)

        # ---- Save --------------------------------------------------- #
        self.output(filename)
        print(f"✅ Professional Strategic PDF Exported: {filename}")
