from fpdf import FPDF
import datetime
import re

class PDFExporter(FPDF):
    def __init__(self, agent_data):
        super().__init__()
        self.agent_data = agent_data
        
        # Color Palette - Using private-like names to avoid collisions with FPDF internals
        self._primary_color = (30, 41, 59)    # Slate 800
        self._secondary_color = (14, 165, 233) # Sky 500
        self._text_color_main = (51, 65, 85)   # Slate 600
        self._bg_color_light = (248, 250, 252) # Slate 50
        
        self.set_auto_page_break(auto=True, margin=25)
        # add_page calls header(), so colors MUST be defined above this line
        self.add_page()
        
    def header(self):
        if self.page_no() == 1:
            # Header Background
            self.set_fill_color(30, 41, 59)
            self.rect(0, 0, 210, 50, 'F')
            
            # Title
            self.set_font("helvetica", "B", 26)
            self.set_text_color(255, 255, 255)
            self.set_xy(10, 15)
            self.cell(190, 15, "STRATEGIC EXECUTION PLAN", align="C")
            
            # Subtitle
            self.set_font("helvetica", "", 10)
            self.set_xy(10, 30)
            self.cell(190, 10, f"Generated by AI Agentic Planner | Groq Core | {datetime.datetime.now().strftime('%d %B %Y')}", align="C")
        else:
            # Simple header for subsequent pages
            self.set_fill_color(30, 41, 59)
            self.rect(0, 0, 210, 15, 'F')
            self.set_font("helvetica", "I", 8)
            self.set_text_color(200, 200, 200)
            self.set_xy(10, 2)
            title = self.agent_data.get('title', 'AI Project')
            self.cell(190, 10, f"Strategic Plan: {self.clean_text(title)}", align="R")

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Confidential Strategic Document - Page {self.page_no()}", align="C")

    def clean_text(self, text):
        if not text: return ""
        replacements = {
            '\u2011': '-', '\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'",
            '\u201c': '"', '\u201d': '"', '\u2022': '*', '\u2026': '...', '\u00a0': ' ',
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        return text.encode('latin-1', 'replace').decode('latin-1')

    def draw_section_box(self, title):
        self.ln(10)
        # Background bar
        self.set_fill_color(241, 245, 249)
        self.rect(10, self.get_y(), 190, 10, 'F')
        # Left border accent
        self.set_fill_color(14, 165, 233)
        self.rect(10, self.get_y(), 2, 10, 'F')
        
        self.set_font("helvetica", "B", 12)
        self.set_text_color(30, 41, 59)
        self.set_x(15)
        self.cell(0, 10, title.upper(), ln=True)
        self.ln(3)

    def write_table_row(self, col1, col2, is_header=False):
        """Helper to create a structured two-column layout."""
        self.set_font("helvetica", "B" if is_header else "", 10)
        
        if is_header:
            self.set_text_color(30, 41, 59)
            self.set_fill_color(226, 232, 240)
            fill = True
        else:
            self.set_text_color(51, 65, 85)
            fill = False

        # Calculate heights
        x_start = 10
        y_start = self.get_y()
        
        # Left Column (e.g. Step #)
        self.set_xy(x_start, y_start)
        self.multi_cell(30, 8, self.clean_text(col1), border=1, align='C', fill=fill)
        h1 = self.get_y() - y_start
        
        # Right Column (e.g. Description)
        self.set_xy(x_start + 30, y_start)
        self.multi_cell(160, 8, self.clean_text(col2), border=1, align='L', fill=fill)
        h2 = self.get_y() - y_start
        
        # Reset Y to the max of both columns
        max_h = max(h1, h2)
        self.set_y(y_start + max_h)

    def process_content_to_table(self, title, content):
        """Intelligently converts AI lists into visual 2-column tables."""
        self.draw_section_box(title)
        
        # Header Row
        self.write_table_row("PHASE / INDEX", "STRATEGIC DESCRIPTION", is_header=True)
        
        lines = str(content).split('\n')
        for line in lines:
            line = line.strip()
            if not line: continue
            
            # Detect list items (1. Step or * Phase)
            match = re.match(r'^([\*\-\d\.]+)\s*(.*)', line)
            if match:
                marker, text = match.groups()
                self.write_table_row(marker, text)
            else:
                # Normal paragraph inside a table section
                self.set_font("helvetica", "", 10)
                self.set_text_color(51, 65, 85)
                self.multi_cell(0, 7, self.clean_text(line))
        self.ln(5)

    def export(self, filename="AI_Strategic_Plan.pdf"):
        # Start content after header
        self.set_y(55)
        
        # SUMMARY CARD
        self.set_fill_color(248, 250, 252)
        self.rect(10, 55, 190, 20, 'F')
        self.set_xy(15, 60)
        self.set_font("helvetica", "B", 14)
        self.set_text_color(30, 41, 59)
        self.cell(0, 10, f"PROJECT: {self.clean_text(self.agent_data.get('title', 'Untitled'))}")
        self.ln(20)

        # 1. VISION
        self.draw_section_box("I. Strategic Vision")
        self.set_font("helvetica", "", 11)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 7, self.clean_text(self.agent_data.get("purpose", "")))

        # 2. EXECUTION TABLE
        self.process_content_to_table("II. Execution Roadmap", self.agent_data.get("flow", ""))

        # 3. ARCHITECTURE
        self.draw_section_box("III. System Architecture")
        self.set_font("courier", "", 9)
        self.set_fill_color(241, 245, 249)
        self.set_text_color(30, 41, 59)
        self.multi_cell(0, 5, self.clean_text(self.agent_data.get("diagram", "")), fill=True, border=1)

        # 4. MARKET INTELLIGENCE TABLE
        self.process_content_to_table("IV. Market Intelligence & Features", self.agent_data.get("market_insights", ""))

        # 5. EXPERT REVIEW
        self.draw_section_box("V. Risk Assessment & Review")
        self.set_font("helvetica", "I", 10)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 7, self.clean_text(self.agent_data.get("feedback_out", "")))

        # Final PDF output
        self.output(filename)
        print(f"✅ Professional Strategic PDF Exported: {filename}")
